### ISSUE TITLE
architecture

### ISSUE THREAD

**Issue by lukemarsden** [modzy/chassis#1]
![modzy-arch](https://user-images.githubusercontent.com/264658/121197792-84332e00-c869-11eb-8b68-77751fb1e8a3.png)

**Comment by DataScienceDeconstructed** [comment]
This is the pre 1.0 architecture. closing, but  to keep around in case we need to reference.

**Comment by caradoxical** [comment]
@all-contributors please add @lukemarsden for doc, projectManagement, ideas, talk, video
