### ISSUE TITLE
Unable to push image to private docker image repository

### ISSUE THREAD

**Issue by roushanatlcci** [modzy/chassis#133]
response = chassis_model.publish(
    model_name="customerepo.com/chassis/digits-sklearn",
    model_version="0.0.1",
    registry_user=username,
    registry_pass=username,
)

The above code always tries to authenticate agains "dockerhub" instead of "customerepo.com". Can anyone please suggest a solution to this.

**Comment by bmunday3** [comment]
Hi @roushanatlcci thank you for your question!

To push images to your private Docker registry, you must install the Chassis service (i.e., the publicly-hosted service only pushes images to Docker Hub). Here is a guide to help you configure your private registry before installing Chassis via helm.

https://chassis.ml/how-to-guides/private-registry/

**Comment by roushanatlcci** [comment]
Thanks @bmunday3 for your response. According to the document the chassisml service can only push to one repo for which it is configured. Is it possible to send the details like repo url and credentials from client side.

**Comment by bmunday3** [comment]
Another great question @roushanatlcci! With Chassis as it stands today (v1), that is correct. It will only push to a registry for which it is configured. 

However, we are actively working on v2 which will include a number of new features. This is a great idea we will take into account. Stay tuned for us to release an alpha version of v2 sometime in the next ~month timeframe appriximately.

**Comment by bmunday3** [comment]
Hey @roushanatlcci ! I know we were able to get around this issue earlier this year, but I wanted to let you know that this process is significantly streamlined with our latest 1.5 release. You can check out the full [release notes](https://chassisml.io/v1.5/release-notes/) for more details, but to summarize, here's how the significant refactor fixes this:
* There are now two methods for building container images: (1) with a local build option, which uses the host machine's Docker daemon to build containers, and (2) a server option, which is a much leaner and more efficient version of what you stood up in your K8s environment
* With the local build option, you can manually push the built containers to a private docker registry of choice
* With the server build option, it is mandatory that you configure it to push directly to a single private docker registry. Check out this [guide](https://chassisml.io/v1.5/guides/install-service/) for more details.

Closing this issue with the above explanation. Please feel free to reach out or open a new issue if you run into additional problems
