### ISSUE TITLE
Issue running both Quickstart and Full Chassis Workflow with chassisml 1.5.0b4

### ISSUE THREAD

**Issue by cch0** [modzy/chassis#147]
**Environment**

```
Python 3.11.6
OS: MacOS 14.1

>pip list 
Package            Version
------------------ ---------
build              1.0.3
certifi            2023.7.22
charset-normalizer 3.3.1
chassisml          1.5.0b4
chassisml-protobuf 4.0.0
click              8.1.7
cloudpickle        2.2.0
docker             6.1.3
grpclib            0.4.7rc1
h2                 4.1.0
hpack              4.0.0
hyperframe         6.0.1
idna               3.4
Jinja2             3.1.2
joblib             1.3.2
MarkupSafe         2.1.3
multidict          6.0.4
numpy              1.26.1
packaging          23.2
pip                23.3.1
pip-tools          7.3.0
protobuf           4.25.0rc2
pyproject_hooks    1.0.0
PyYAML             6.0.1
requests           2.31.0
scikit-learn       1.3.0
scipy              1.11.3
setuptools         68.2.2
threadpoolctl      3.2.0
urllib3            2.0.7
validators         0.22.0
websocket-client   1.6.4
wheel              0.41.3
```

**How is Chassisml installed?**

Initially, I was not able to use the instruction provided.
```
>pip install --pre chassisml[quickstart]

zsh: no matches found: chassisml[quickstart]
```

Then, I did these,

```
>pip install scikit-learn==1.3.0
>pip install --pre chassisml
```

**Issue with Quickstart**

Following the instructions at https://chassisml.io/v1.5/getting-started/quickstart/, I was able to build the docker image locally.
<br>
Then I executed the provided inference code

```
from chassis.client import OMIClient
from chassis.guides import DigitsSampleData

# Execute the test_container method to spin up the container, run inference, and return the results
res = OMIClient.test_container(container_name="my-first-chassis-model", inputs=DigitsSampleData, pull=False)
# Parse results from output item 
result = res.outputs[0].output["results.json"]
# View results
print(f"Result: {result}")
```

<br>
and saw this error

```
    result = res.outputs[0].output["results.json"]
             ^^^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'outputs'
```

<br>

**Issue with Full Chassis Workflow**

Following the instructions at https://chassisml.io/v1.5/getting-started/full-workflow/, I was also able to build another image locally.

No issue running this command to get the container up

```
docker run --rm -it -p 45000:45000 my-first-chassis-model
```

Then I executed the provided inference code

```
from chassis.client import OMIClient
from chassis.guides import DigitsSampleData

# Instantiate OMI Client connection to model running on localhost:45000 
with OMIClient("localhost", 45000) as client:
    # Call and view results of status RPC 
    status = client.status()
    print(f"Status: {status}")
    # Submit inference with quickstart sample data
    res = client.run(DigitsSampleData)
    # Parse results from output item 
    result = res.outputs[0].output["results.json"]
    # View results
    print(f"Result: {result}")

```

<br>

and saw error when running the inference code

```
    with OMIClient("localhost", 45000) as client:
TypeError: 'OMIClient' object does not support the context manager protocol
```

**Comment by cch0** [comment]
Correction. The issue I had with regard to chassisml install has something to do with fact that I am using `zsh`.  No issue to install `chassisml[quickstart]` after switching to `bash`.

**Comment by caradoxical** [comment]
I believe this issue should be resolved by installing the latest version of the package and referring to the updated tutorial guidelines on chassisml.io. Also, the zsh error shouldn't be an issue anymore either as we updated the tutorial documentation so that copying and pasting the pip command should work on any shell now (zsh expects quotes around specific submodule installs via pip). If these issues persists, just let us know and we'll open it back up and take a look. Thanks again for sharing and sorry for the inconvenience.

**Comment by cch0** [comment]
Thank you for the quick turn around. 
I have verified that both notebook and non-notebook examples are working fine.
