### ISSUE TITLE
Reduce containerized image size

### ISSUE THREAD

**Issue by carmilso** [modzy/chassis#19]
At the moment, final image weighs around 691MB. This is due to the fact that full python lib binary is copied to environment folder when packaging conda (so you don't need to use a docker image with python already installed). This python binary weighs 462MB, which represents almost the 70% of the whole image.

It would be needed to find some way to not copy the python binary and use the one from the system so that we were able to leverage a docker image like python:3.8-slim, that only weighs 114MB. Doing this we could end with an image of 343MB, which is half of what we have now.

**Comment by bmunday3** [comment]
Closing because container size is optimized in latest 1.5 release
