### ISSUE TITLE
Chassis Documentation Upgrades

### ISSUE THREAD

**Issue by DataScienceDeconstructed** [modzy/chassis#54]
We need to develop documentation both for users who want to install and run chassis as is ... and for developers who want to contribute to chassis. The installs and setups here are different so that Kaniko can run locally on a machine for the devs.

**Comment by DataScienceDeconstructed** [comment]
additionally, the docs need to cover Chassisml SDK

**Comment by DataScienceDeconstructed** [comment]
@bmunday3 does your PR resolve this?

**Comment by bmunday3** [comment]
@DataScienceDeconstructed it does yes
