### ISSUE TITLE
Add explainability and drift support + examples

### ISSUE THREAD

**Issue by DataScienceDeconstructed** [modzy/chassis#55]
Make a list of most popular output configurations and ensure that examples exist in the chassis repo. output only, output + explainability, output+ explainability + drift, also across a DL and standard model representation.

Add a section in docs to point reader to examples.

**Comment by DataScienceDeconstructed** [comment]
clarifying point. make sure that the chassis docs cover export examples and that the notebook examples point back to the docs for autosupported items.

**Comment by bmunday3** [comment]
Modified scope of this to coincide with explainability support

**Comment by bmunday3** [comment]
Accepted as a roadmap item for v1.6 release (https://github.com/orgs/modzy/projects/4?pane=issue&itemId=33138982).
