### ISSUE TITLE
add conda checks to see if modules available

### ISSUE THREAD

**Issue by DataScienceDeconstructed** [modzy/chassis#72]
when packaging models cross platform we need a way to check and see if the packages are available on the target platform.

possibly helpful: https://stackoverflow.com/questions/48740705/check-in-python-if-a-conda-package-exist

**Comment by DataScienceDeconstructed** [comment]
this is related to #74

**Comment by bmunday3** [comment]
Conda has been removed entirely in the our latest v1.5 release, so this no longer is an issue.
