### ISSUE TITLE
Bug - check user environment is available in conda

### ISSUE THREAD

**Issue by DataScienceDeconstructed** [modzy/chassis#74]
right now we don't check that all the dependencies for python are available in the conda channels before we start building the user's container. This can cause a container build failure when the user's environment running the Chassis SDK isn't producible from conda repos. e.g. the user uses a version of python conda doesn't support such as 3.9.10 . The expected behavior is that Chassis would use a search command to confirm the environment is reproducible before attempting the build.

**Comment by bmunday3** [comment]
See Issue #72
