### ISSUE TITLE
Allow creation of private container images

### ISSUE THREAD

**Issue by bmunday3-zz** [modzy/chassis#76]
Currently, the chassis service will publish container images as a public image on Dockerhub, but it would be great if it was possible to specify a `private` flag to deploy container images that require credentials to pull.

**Comment by DataScienceDeconstructed** [comment]
@bmunday3 to clarify... are we talking about submitting to a private dockerhub repo or to a nonDockerhub repo here?

**Comment by bmunday3** [comment]
@DataScienceDeconstructed for this one, I'm referring to creating just a private dockerhub repo.

**Comment by caradoxical** [comment]
@all-contributors please add @bmunday3  for code
