### ISSUE TITLE
Tensorflow/Keras framework does not seem to be supported

### ISSUE THREAD

**Issue by bmunday3** [modzy/chassis#80]
In doing some experimentation, chassis throws a pickling error when trying to build an image from a tf/keras model. 

Since mlflow has built direct support for both tf and keras (built in "flavors"), and chassis currently uses the generic `mlflow.pyfunc` flavor, this issue may be resolvable if a new flavor was created, say `mlflow-tf` or something like this, that leverages the `mlflow.tensorflow` or `mlflow.keras` ml model flavors directly. 

This new flavor would essentially be a duplicate of the existing [chassis/service/flavours/mlflow](https://github.com/modzy/chassis/tree/main/service/flavours) flavor, but would use the tf/keras flavor directly.

**Comment by bmunday3** [comment]
More detailed information:

The main difference between `mlflow.pyfunc.save_model` and `mlflow.tensorflow.save_model` is the TF flavor requires an already serialized TF model, saved using the `tf.saved_model.save` method. Moreover, the `mlflow.tensorflow.save_model` method takes three TF-specific as arguments: (1) `<some-path>` that contains the properly saved tf model, (2) a list of tf metagraph tags, and (3) a signature definition key, which identifies the input/output signature associated with the model. These three items are directly associated with the serialized TF model. 

As a result, this [part](https://github.com/modzy/chassis/blob/main/chassisml-sdk/chassisml/chassisml.py#L176-L177) of the Chassis SDK will not work for TF models. Currently, this code takes in a [ChassisModel](https://github.com/modzy/chassis/blob/main/chassisml-sdk/chassisml/chassisml.py#L35) object as the `python_model` parameter to the `mlflow.pyfunc.save_model` method. Two things need to be changed to support TF-specific models:

1. The construction of the `ChassisModel` object needs to be changed (or can take optional TF specific values).
2. When the mlflow save model execution occurs, TF models need to be saved using the `mlflow.tensorflow.save_model` method instead of the generic pyfunc method. This would assume the proper TF objects are accessible, most realistically through the `ChassisModel` object.

**Comment by bmunday3** [comment]
Notes following discussion on this issue 3/24:

- It appears that unlike the generic `mlflow.pyfunc` model class, where you can customized the `predict` method (passed through in Chassis as `process_fn` or `batch_process_fn`, saving a model in `mlflow.tensorflow` format does not allow you to overwrite the `predict` method.
- To successfully save, load, and then run `predict` on a tensorflow model in mlflow format, it must be saved as `mlflow.tensorflow` then loaded back and run inference in three very specific lines of code.
- We likely need to write another custom class where we inherit from the `mlflow.tensorflow` class and then overwrite the `predict` method.

**Comment by brooks-ulap** [comment]
Hi there, I was wondering if this ticket was closed as completed? I am trying to build a TensorFlow model with Chassis now that I have successfully built a sci-kit model into a container. The documentation page says "Coming Soon" under the examples for TF + Keras. Could someone help point me in the right direction to get started with building TF through Chassis?

**Comment by bmunday3** [comment]
Hi @brooks-ulap, thanks so much for your question! Do you happen to be working with a TF v2 model (e.g., something like this https://www.tensorflow.org/tutorials/quickstart/beginner#build_a_machine_learning_model)?

If so, that should be supported. We have not yet put an example on the docs site, but here's a quick block of sample code that should put you in the right direction.

Let's use this tutorial as an example model: https://www.tensorflow.org/tutorials/images/cnn.

Assuming you follow this in a notebook, you could append this chassis code to build a container image from it:

```python
import chassisml

# define process function
def process(input_bytes):
    
    img = tf.io.decode_image(input_bytes, channels=3)
    img = tf.expand_dims(img, 0)
    img = tf.image.resize(img, [32,32])

    preds = model.predict(img)    

    return preds

# instantiate chassis client and create model object
chassis_client = chassisml.ChassisClient("https://chassis.app.modzy.com/")
chassis_model = chassis_client.create_model(process_fn=process)

# test model with sample iamge
sample_filepath = "image.jpg" # assumes you have a ciphar sample image saved as "./image.jpg"
results = chassis_model.test(sample_filepath)
print(results)

# publish model
dockerhub_user = "<insert-docker-user>"
dockerhub_pass = "<insert-docker-pass>"

response = chassis_model.publish(
    model_name="TF Keras Test Image Classification",
    model_version="0.0.1",
    registry_user=dockerhub_user,
    registry_pass=dockerhub_pass,
)
```
