### ISSUE TITLE
Ensure test drive tutorial works well

### ISSUE THREAD

**Issue by lukemarsden** [modzy/chassis#9]
Saumil will ask Brad to do it

Do this after modzy v2 api is ready so that we can test pushing to docker hub and then manually test in modzy after that.

**Comment by lukemarsden** [comment]
I've tested it and it works!

Please share any additional feedback with @carmilso. Thanks!

**Comment by bmunday3** [comment]
I tested the test drive feature yesterday and again just now, and everything worked until I checked the status of the job after it was launched. Four times now I have received this error:
```
{'active': None,
 'completion_time': None,
 'conditions': [{'last_probe_time': 'Wed, 28 Jul 2021 13:52:07 GMT',
   'last_transition_time': 'Wed, 28 Jul 2021 13:52:07 GMT',
   'message': 'Job has reached the specified backoff limit',
   'reason': 'BackoffLimitExceeded',
   'status': 'True',
   'type': 'Failed'}],
 'failed': 1,
 'start_time': 'Wed, 28 Jul 2021 13:51:56 GMT',
 'succeeded': None}
```
And when I check the running pods in the SSH tab, I see this:
`default            chassis-builder-job-d069dab3-ae2d-487d-a04b-2f6d3613528e-ll5zm   0/1     Error     0          21s`
