### ISSUE TITLE
Model result response should be a data URI

### ISSUE THREAD

**Issue by n8mellis** [modzy/chassis#94]
To make it more obvious that the result is base 64 encoded and to also indicate what kind of file it represents, the model result should be formatted as a data URI which will indicate not only the MIME type of the file but also the encoding used.

For more info on data URIs, see https://en.wikipedia.org/wiki/Data_URI_scheme

**Comment by caradoxical** [comment]
@all-contributors please add @n8mellis for ideas, infra, code
